#!/bin/sh

LOGFILE="/var/log/misc-modules-start-stop.log"

case "$1" in
    start)
	echo "loading faulty driver" >> $LOGFILE
	
	module="faulty"
        device="faulty"
	mode="644"

	set -e
	# Group: since distributions do it differently, look for wheel or use staff
	# These are groups which correspond to system administrator accounts
	if grep -q '^staff:' /etc/group; then
	    group="staff"
	else
	    group="wheel"
	fi

	insmod /lib/modules/$(uname -r)/extra/$module.ko || exit 1
	echo "Get the major number (allocated with allocate_chrdev_region) from /proc/devices" >> $LOGFILE
	major=$(awk "\$2==\"$module\" {print \$1}" /proc/devices)
	if [ ! -z ${major} ]; then
	    echo "Remove any existing /dev node for /dev/${device}" >> $LOGFILE
	    rm -f /dev/${device}
	    echo "Add a node for our device at /dev/${device} using mknod" >> $LOGFILE
	    mknod /dev/${device} c $major 0
	    echo "Change group owner to ${group}" >> $LOGFILE
	    chgrp $group /dev/${device}
	    echo "Change access mode to ${mode}" >> $LOGFILE
	    chmod $mode  /dev/${device}
	else
	    echo "No device found in /proc/devices for driver ${module} (this driver may not allocate a device)" >> $LOGFILE
	fi

	echo "starting hello module" >> $LOGFILE
	modprobe hello
	;;
    stop)
	echo "Stopping hello module" >> $LOGFILE
	rmmod hello || exit 1

        echo "Stopping faulty driver" >> $LOGFILE
	# invoke rmmod with all arguments we got
	rmmod faulty || exit 1

	# Remove stale nodes

	rm -f /dev/faulty
	;;
    *)
        echo "Usage: $0 {start | stop}" >> $LOGFILE
    exit 1
esac
